use_frameworks!

target 'WKWebViewWithURLProtocol_Example' do
  pod 'WKWebViewWithURLProtocol', :path => '../'

  target 'WKWebViewWithURLProtocol_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
